version: '3.3'

services:
  mongodb:
    image: mongo:4.0.6
    container_name: logger_mongodb
    environment:
      - MONGO_INITDB_DATABASE=logger
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - logger_data:/data/db
      - logger_conf:/data/configdb
    networks:
      - def
    restart: always

  logger:
    # build will get tagged with 'image'
    build:
      context: ./logger
      args:
          - REPO_BRANCH=${CAS_LOGGER_RELEASE}
          - SECRET_KEY=secret-key
          - SECURITY_PASSWORD_SALT=a324agfh[z
          - SECRET_DB_NAME=logger
    image: cas.logger:1.0
    container_name: logger
    ports:
      - 8120:8120
    networks:
      - def
    depends_on:
      - mongodb
    restart: always


networks:
  def:
    driver: bridge


volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  logger_data:
  logger_conf:
