web:
  image: 'gitlab/gitlab-ee:latest'
  restart: unless-stopped
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://localhost:8929'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '9001:9001'
    - '2224:22'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'
  restart: unless-stopped
